### ISSUE TITLE
[🐞] Express adapter with ssg fails to build inside docker

### ISSUE THREAD

**Issue by noc2spam** [QwikDev/qwik#4877]
### Which component is affected?
Express Adapter

### Describe the bug

I am using express adepter. I want to have a sitemap.xml created automatically during each build. For achieving that, I put the following inside the vite.config.ts:

```
ssg: {
     include: ["/*"],
     sitemapOutFile: "sitemap.xml",
 },
```

But it fails with the following error code:

```
5.472 Starting Qwik City SSG...
5.542 Error: getaddrinfo ENOTFOUND mysql
5.542     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
5.542   errno: -3008,
5.542   code: 'ENOTFOUND',
5.542   syscall: 'getaddrinfo',
5.542   hostname: 'mysql',
5.542   fatal: true
5.542 }
5.544 error []
5.559 Error: getaddrinfo ENOTFOUND mysql
5.559     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
5.559   errno: -3008,
5.559   code: 'ENOTFOUND',
5.559   syscall: 'getaddrinfo',
5.559   hostname: 'mysql',
5.559   fatal: true
5.559 }
5.568 
5.568 Error during SSG
5.568 
5.568   Pathname: /
5.569 dist/index.html
5.569   Plugin: qwik-ssg
6.293 dist/contact-us/index.html
6.382 dist/thank-you/index.html
6.407 error during build:
6.407 undefined
```

The problem seems to be the host, which in my case is `mysql`, since I am using docker to host the stack. It otherwise works just fine, so it's not a problem with wrong host. 

I guess this happens because `mysql` has not started yet during build time? 
Am I approaching this in a wrong way? 

Please note that mysql is not accesible externally. This container communicates with the other containers internally. 

### Reproduction

N/A

### Steps to reproduce

`docker compose up --build`

My docker compose file looks like the following:

```
version: '3.8'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: of-lander-frontend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./uploads:/usr/src/app/dist/uploads/
    ports:
      - 2999:2999
  mysql:
    container_name: of-lander-mysql
    image: mariadb:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
```

Qwik container's Dockerfile looks like this:

```
FROM node:19.2-alpine3.15 as build

WORKDIR /usr/src/app

COPY ./frontend/package.json ./
COPY ./.env ./.env
RUN npm install

COPY ./frontend/ ./

RUN npm run build.client
RUN npm run build.server

FROM node:19.2-alpine3.15 as production

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/server ./server
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/.env ./.env.local

EXPOSE 2999

CMD [ "node", "server/entry.express"]
```

### System Info

Ubuntu 20.10, Docker 24.0.4. Docker compose v2.19.1.

### Additional Information

Extremely sorry if I did not use the issue  template correctly. Still very new to Qwik. Please do correct me so that I can update the post as needed.
